config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :order_products
  resources :orders
  resources :product_quantities
  resources :warehouses
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products

  OutOfStockError = Class.new(StandardError)

  def add_product(product, quantity = 1)
    raise OutOfStockError.new unless product.in_stock?

    order_product = order_products.find { |op| op.product_id == product.id }

    if order_product.present?
      order_product.update(quantity: order_product.quantity + 1)
    else
      order_products.create!(product: product, quantity: quantity)
    end
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_quantities

  monetize :price_cents

  def in_stock?
    total_quantity.positive?
  end

  def total_quantity
    product_quantities.map(&:quantity).sum
  end
end

app/models/product_quantity.rb
class ProductQuantity < ApplicationRecord
  belongs_to :product
  belongs_to :warehouse
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  has_many :product_quantities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/order_products_controller.rb
class OrderProductsController < ApplicationController
  before_action :set_order_product, only: [:show, :edit, :update, :destroy]

  # GET /order_products
  def index
    @order_products = OrderProduct.all
  end

  # GET /order_products/1
  def show
  end

  # GET /order_products/new
  def new
    @order_product = OrderProduct.new
  end

  # GET /order_products/1/edit
  def edit
  end

  # POST /order_products
  def create
    @order_product = OrderProduct.new(order_product_params)

    if @order_product.save
      redirect_to @order_product, notice: 'Order product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /order_products/1
  def update
    if @order_product.update(order_product_params)
      redirect_to @order_product, notice: 'Order product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /order_products/1
  def destroy
    @order_product.destroy
    redirect_to order_products_url, notice: 'Order product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_product
      @order_product = OrderProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_product_params
      params.require(:order_product).permit(:product_id, :order_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:status, :payment_status, :delivery_status, :delivery_address)
    end
end

app/controllers/product_quantities_controller.rb
class ProductQuantitiesController < ApplicationController
  before_action :set_product_quantity, only: [:show, :edit, :update, :destroy]

  # GET /product_quantities
  def index
    @product_quantities = ProductQuantity.all
  end

  # GET /product_quantities/1
  def show
  end

  # GET /product_quantities/new
  def new
    @product_quantity = ProductQuantity.new
  end

  # GET /product_quantities/1/edit
  def edit
  end

  # POST /product_quantities
  def create
    @product_quantity = ProductQuantity.new(product_quantity_params)

    if @product_quantity.save
      redirect_to @product_quantity, notice: 'Product quantity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /product_quantities/1
  def update
    if @product_quantity.update(product_quantity_params)
      redirect_to @product_quantity, notice: 'Product quantity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /product_quantities/1
  def destroy
    @product_quantity.destroy
    redirect_to product_quantities_url, notice: 'Product quantity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_quantity
      @product_quantity = ProductQuantity.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_quantity_params
      params.require(:product_quantity).permit(:product_id, :warehouse_id, :quantity)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  # GET /warehouses
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      redirect_to @warehouse, notice: 'Warehouse was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /warehouses/1
  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse, notice: 'Warehouse was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /warehouses/1
  def destroy
    @warehouse.destroy
    redirect_to warehouses_url, notice: 'Warehouse was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_products_helper.rb
module OrderProductsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/product_quantities_helper.rb
module ProductQuantitiesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParallelTestsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_products/_form.html.erb
<%= form_with(model: order_product) do |form| %>
  <% if order_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order_product.errors.count, "error") %> prohibited this order_product from being saved:</h2>

      <ul>
        <% order_product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :order_id %>
    <%= form.text_field :order_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/order_products/edit.html.erb
<h1>Editing Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Show', @order_product %> |
<%= link_to 'Back', order_products_path %>

app/views/order_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Products</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_products.each do |order_product| %>
      <tr>
        <td><%= order_product.product_id %></td>
        <td><%= order_product.order_id %></td>
        <td><%= link_to 'Show', order_product %></td>
        <td><%= link_to 'Edit', edit_order_product_path(order_product) %></td>
        <td><%= link_to 'Destroy', order_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order Product', new_order_product_path %>

app/views/order_products/new.html.erb
<h1>New Order Product</h1>

<%= render 'form', order_product: @order_product %>

<%= link_to 'Back', order_products_path %>

app/views/order_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @order_product.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_product.order_id %>
</p>

<%= link_to 'Edit', edit_order_product_path(@order_product) %> |
<%= link_to 'Back', order_products_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :payment_status %>
    <%= form.number_field :payment_status %>
  </div>

  <div class="field">
    <%= form.label :delivery_status %>
    <%= form.number_field :delivery_status %>
  </div>

  <div class="field">
    <%= form.label :delivery_address %>
    <%= form.text_field :delivery_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Payment status</th>
      <th>Delivery status</th>
      <th>Delivery address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= order.payment_status %></td>
        <td><%= order.delivery_status %></td>
        <td><%= order.delivery_address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Payment status:</strong>
  <%= @order.payment_status %>
</p>

<p>
  <strong>Delivery status:</strong>
  <%= @order.delivery_status %>
</p>

<p>
  <strong>Delivery address:</strong>
  <%= @order.delivery_address %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/product_quantities/_form.html.erb
<%= form_with(model: product_quantity) do |form| %>
  <% if product_quantity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_quantity.errors.count, "error") %> prohibited this product_quantity from being saved:</h2>

      <ul>
        <% product_quantity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :warehouse_id %>
    <%= form.text_field :warehouse_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_quantities/edit.html.erb
<h1>Editing Product Quantity</h1>

<%= render 'form', product_quantity: @product_quantity %>

<%= link_to 'Show', @product_quantity %> |
<%= link_to 'Back', product_quantities_path %>

app/views/product_quantities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Quantities</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Warehouse</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_quantities.each do |product_quantity| %>
      <tr>
        <td><%= product_quantity.product_id %></td>
        <td><%= product_quantity.warehouse_id %></td>
        <td><%= product_quantity.quantity %></td>
        <td><%= link_to 'Show', product_quantity %></td>
        <td><%= link_to 'Edit', edit_product_quantity_path(product_quantity) %></td>
        <td><%= link_to 'Destroy', product_quantity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Quantity', new_product_quantity_path %>

app/views/product_quantities/new.html.erb
<h1>New Product Quantity</h1>

<%= render 'form', product_quantity: @product_quantity %>

<%= link_to 'Back', product_quantities_path %>

app/views/product_quantities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_quantity.product_id %>
</p>

<p>
  <strong>Warehouse:</strong>
  <%= @product_quantity.warehouse_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product_quantity.quantity %>
</p>

<%= link_to 'Edit', edit_product_quantity_path(@product_quantity) %> |
<%= link_to 'Back', product_quantities_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products. Yo!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/edit.html.erb
<h1>Editing Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Show', @warehouse %> |
<%= link_to 'Back', warehouses_path %>

app/views/warehouses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Warehouses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @warehouses.each do |warehouse| %>
      <tr>
        <td><%= warehouse.name %></td>
        <td><%= warehouse.location %></td>
        <td><%= link_to 'Show', warehouse %></td>
        <td><%= link_to 'Edit', edit_warehouse_path(warehouse) %></td>
        <td><%= link_to 'Destroy', warehouse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Warehouse', new_warehouse_path %>

app/views/warehouses/new.html.erb
<h1>New Warehouse</h1>

<%= render 'form', warehouse: @warehouse %>

<%= link_to 'Back', warehouses_path %>

app/views/warehouses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @warehouse.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @warehouse.location %>
</p>

<%= link_to 'Edit', edit_warehouse_path(@warehouse) %> |
<%= link_to 'Back', warehouses_path %>